# Generated by Django 3.0.5 on 2020-04-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('TZ', 'Tanzania')], default='TZ', max_length=3),
        ),
    ]
