# Generated by Django 3.0.4 on 2020-04-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productimage_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='producttag',
            name='products',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
    ]
